# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# GISRoutingTool8-GriddedRaster.py
# Created on: 2016-10-03 14:23:59.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: GISRoutingTool8-GriddedRaster <Batch_Delineated_Watersheds> <Input_Path> <VIC_Cell_Number_Raster> <Output_Path> [<Field ID from Watersheds>]
# Description: 
# Extract routing model statistics for each watershed.  This uses the Batch Watershed polygon file from ArcHydro.  Travel times for the current watershed are adjusted by subtracting the travel time from the current outlet to the basin outlet for all pixels.  This sets the outlet travel time to zero.  Any values that end up negative (because they drain out of the watershed) are set to No Data. Solution elements (zones) with less than Thres percent of the zone contributing to watershed streamflow are excluded.  Then the mean and standard deviation of travel times are found for each Zone.  Output for each defined watershed is a table with zonal statistics.  You will need the mean and standard deviation from the table to create routing model input files.  The mask file can be created by setting any zones with values to '1' to indicate that they should be included.  Zones contributing less than Thres have already been removed from the output zonal statistics table.
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import sys

# Load required toolboxes
#arcpy.ImportToolbox("Model Functions")

# Get current workspace
CurrSpace = arcpy.env.workspace

# Script arguments
Batch_Delineated_Watersheds = arcpy.GetParameterAsText(0)
if Batch_Delineated_Watersheds == '#' or not Batch_Delineated_Watersheds:
    Batch_Delineated_Watersheds = "Watershed" # provide a default value if unspecified
InputField = arcpy.GetParameter

Input_Path = arcpy.GetParameterAsText(1)
if Input_Path == '#' or not Input_Path:
    Input_Path = "RoutingLayers" # provide a default value if unspecified

VIC_Cell_Number_Raster = arcpy.GetParameterAsText(2)
if VIC_Cell_Number_Raster == '#' or not VIC_Cell_Number_Raster:
    VIC_Cell_Number_Raster = "LdasCellNum_SimRes" # provide a default value if unspecified

Output_Path = arcpy.GetParameterAsText(3)
if Output_Path == '#' or not Output_Path:
    Output_Path = "GISRoutingInput" # provide a default value if unspecified

FieldID = arcpy.GetParameterAsText(4)
if FieldID == '#' or not FieldID:
    FieldID = "HydroID" # provide a default value if unspecified

# Local variables:
Zonal_Table_Input_Path = Input_Path + "\\" + "ZonalTables"

# Get list of watershed index numbers
wShedNums = [row[0] for row in arcpy.da.SearchCursor(Batch_Delineated_Watersheds, FieldID)]

# Process each watershed
for wShed in wShedNums:

    # Build filenames for the current watershed
    CurrentZoneGrid = Zonal_Table_Input_Path + "\\" + "ZonalStats_%i.dbf" % wShed
    Mean_Raster = Output_Path + "\\" + "WS%i_ttMean" % wShed
    Output_Mean_Travel_Time_ASCII_raster_file = Output_Path + "\\" + "WS%i_ttMean.TXT" % wShed
    Std_Dev_Raster = Output_Path + "\\" + "WS%i_ttStd" % wShed
    Output_Std_Dev_of_Travel_Time_ASCII_raster_file = Output_Path + "\\" + "WS%i_ttStd.TXT" % wShed
    Watershed_Mask = Output_Path + "\\" + "WS%i_Mask" % wShed
    Output_Mask_ASCII_raster_file = Output_Path + "\\" + "WS%i_Mask.TXT" % wShed

    # Process: Iterate Feature Selection
    #arcpy.IterateFeatureSelection_mb(Batch_Delineated_Watersheds, "HydroID #", "false")

    # Process: Add Join
    #arcpy.AddJoin_management(VIC_Cell_Number_Raster, "VAT_%s.Value" % VIC_Cell_Number_Raster, CurrentZoneGrid, "GRIDCODE", "KEEP_ALL")
    arcpy.AddJoin_management(VIC_Cell_Number_Raster, "Value", CurrentZoneGrid, "GRIDCODE", "KEEP_ALL")

    # Process: Lookup - Mean Travel Time
    arcpy.gp.Lookup_sa(VIC_Cell_Number_Raster, "ZonalStats_%i.MEAN" % wShed, Mean_Raster)

    # Process: Raster to ASCII - Mean Travel Time
    arcpy.RasterToASCII_conversion(Mean_Raster, Output_Mean_Travel_Time_ASCII_raster_file)

    # Process: Lookup - Std Dev of Travel Time
    arcpy.gp.Lookup_sa(VIC_Cell_Number_Raster, "ZonalStats_%i.STD" % wShed, Std_Dev_Raster)

    # Process: Raster to ASCII - Std Dev of Travel Time
    arcpy.RasterToASCII_conversion(Std_Dev_Raster, Output_Std_Dev_of_Travel_Time_ASCII_raster_file)

    # Process: Con
    arcpy.gp.Con_sa(Mean_Raster, "1", Watershed_Mask, "", "VALUE > 0")

    # Process: Raster to ASCII - Watershed Mask
    arcpy.RasterToASCII_conversion(Watershed_Mask, Output_Mask_ASCII_raster_file)

    # Process: Remove join before looping to next watershed
    arcpy.RemoveJoin_management(VIC_Cell_Number_Raster)